version: "3"
services:
  next:
    container_name: next
    build:
      context: ./Docker/nextjs
    ports:
      - 3011:3011
    volumes:
      - ./src:/var/www
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    env_file:
      - .env
